# Run docker-compose up
# Live long and prosper
version: "2"
services:
  rabbitmq:
    container_name: skf-rabbitmq_container
    image: rabbitmq:3.8.19
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin-skf-secret
    ports:
        - "5672:5672"
        - "15672:15672"
  
  mysql:
    container_name: skf-mysql_container
    image: blabla1337/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "skf"
      MYSQL_ROOT_PASSWORD: "admin-skf-secret"
      MYSQL_DEFAULT_PASS: "admin-skf-secret"
      MYSQL_DEFAULT_USER: "root"
    ports:
      - "3306:3306"
  
  nginx:
    container_name: skf-nginx_container
    restart: always
    image: nginx
    volumes:
      - ./Docker/compose/minimal-site.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  skf-angular:
    container_name: skf-angular_container
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    image: "skf-angular"
    environment:
      - FRONTEND_URI=http://localhost
      - AUTH_METHOD=skiploginprovider

  skf-api:
    container_name: skf-api_container
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    volumes:
      - ~/.kube/config:/home/user_api/.kube/config
    image: "skf-api"
    environment:
      - SKF_FLASK_DEBUG=False
      - SKF_API_URL=skf-api://api
      - SKF_TESTING=False
      - SKF_DB_URL=mysql+pymysql://root:admin-skf-secret@mysql/skf?charset=utf8mb4
      - SKF_JWT_SECRET=please_change_this_value_to_be_random
      - SKF_LABS_DOMAIN=http://localhost
      - SKF_LABS_DEPLOY_MODE=port
      - RABBIT_MQ_CONN_STRING=rabbitmq
      - LABS_KUBE_CONF=~/.kube/config